### Please Read the Question carefully and write the code.

1. Input a List from user and convert the list to a numpy array.

In [ ]:
import numpy as np

In [ ]:
user_input = input("Enter list of intigers separated by space: ")
user_list = list(map(int, user_input.split()))
# print(user_list)
user_array = np.array(user_list)
print(user_array)
# print(user_array.dtype)

Enter list of intigers separated by space: 1 2 3 4 5
[1 2 3 4 5]


2. Create a 4 X 4 identity matrix using numpy and reshape it into 8 X 2 if possible.

In [ ]:
user_matrix = np.zeros((4, 4))
# print(user_matrix)
resape_matrix = user_matrix.T.reshape(8, 2)
print(resape_matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


3. Create two numpy array and perform arithmetic operation on it.

In [ ]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])
print(array1+array2)

[ 7  9 11 13 15]


4. Find the elements that are multiple of 3 as well as divisable by 5 from a numpy array.

In [ ]:
user_input = input()
# user_list = list(map(int, user_input.split()))
user_array = np.array(user_list)
for x in user_array:
  if x%3==0 and x%5==0: print(x)

2 3 4 15 23 26 30
15
30


5. Create a new array from a given array, swapping first and last, second and third columns

In [ ]:
user_array = np.array([2, 3, 4, 15, 23, 26, 30])
user_array[0], user_array[-1] = user_array[-1], user_array[0]
print(user_array)
print('\n')
user_matrix = np.array([[1,2,3,4],[2,3,5,7],[2,6,8,3]])
print(user_matrix)
print('\n')
user_matrix[:,[1,2]] = user_matrix[:,[2,1]]
print(user_matrix)

[30  3  4 15 23 26  2]


[[1 2 3 4]
 [2 3 5 7]
 [2 6 8 3]]


[[1 3 2 4]
 [2 5 3 7]
 [2 8 6 3]]


6. Multiply a 4x3 matrix by a 3x3 matrix (first check the multipication is possible or not)

In [ ]:
user_matrix1 = np.array([[1,2,3],[2,3,5],[2,6,8],[2,7,4]])
user_matrix2 = np.array([[1,2,3],[2,3,5],[2,6,8]])
if user_matrix1.shape[1] == user_matrix2.shape[0]:
  result = np.dot(user_matrix1, user_matrix2)
  print(result)

[[ 11  26  37]
 [ 18  43  61]
 [ 30  70 100]
 [ 24  49  73]]


7. Create a 6 X 6 matrix and cut the lower 3 X 3 matrix from the biggest one.

In [ ]:
big_matrix = np.array([[1, 2, 3, 4, 5, 6],
                       [7, 8, 9, 10, 11, 12],
                       [13, 14, 15, 16, 17, 18],
                       [19, 20, 21, 22, 23, 24],
                       [25, 26, 27, 28, 29, 30],
                       [31, 32, 33, 34, 35, 36]])

small_matrix = big_matrix[3: , :3]
print(small_matrix)

[[19 20 21]
 [25 26 27]
 [31 32 33]]


8. Take a 2D numpy array and sort it in assending and dissending order.

In [ ]:
ascending_row = np.sort(small_matrix, axis=0)
descending_row = np.sort(small_matrix, axis=0)[::-1]
print(ascending_row)
print('\n')
print(descending_row)

[[19 20 21]
 [25 26 27]
 [31 32 33]]


[[31 32 33]
 [25 26 27]
 [19 20 21]]


9. Convert a Python dictionary to Numpy array.

In [ ]:
my_dic = {'a': [1, 2, 3],
           'b': [4, 5, 6],
           'c': [7, 8, 9]}
print(my_dic)
my_list = list(my_dic.values())
my_array = np.array(my_list)
print(my_array)

{'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]}
[[1 2 3]
 [4 5 6]
 [7 8 9]]


10. Write a code that show all the numpy array generation procedure.

In [50]:
# Generate a 3x3 array of zeros
zeros_array = np.zeros((3, 3))
print("Zeros array:\n", zeros_array)

# Generate a 3x3 array of ones
ones_array = np.ones((3, 3))
print("\nOnes array:\n", ones_array)

# Generate a 3x3 array of random numbers
random_array = np.random.rand(3, 3)
print("\nRandom array:\n", random_array)

# Generate a 3x3 array of random integers
random_int_array = np.random.randint(low=0, high=10, size=(3, 3))
print("\nRandom integer array:\n", random_int_array)

# Generate a 3x3 array of evenly spaced values
evenly_spaced_array = np.linspace(start=0, stop=10, num=9).reshape(3, 3)
print("\nEvenly spaced array:\n", evenly_spaced_array)

# Generate a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\nIdentity matrix:\n", identity_matrix)


Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Random array:
 [[0.97052764 0.58150384 0.37729395]
 [0.36349629 0.91887917 0.59380427]
 [0.81706317 0.60248317 0.79456667]]

Random integer array:
 [[7 8 2]
 [5 6 3]
 [5 5 4]]

Evenly spaced array:
 [[ 0.    1.25  2.5 ]
 [ 3.75  5.    6.25]
 [ 7.5   8.75 10.  ]]

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
